### ISSUE TITLE
Please add example code to estimate alpha channel on one image

### ISSUE THREAD

**Issue by albirrkarim** [hustvl/ViTMatte#1]
and also demo code using Google Colab

Thanks

**Comment by JingfengYao** [comment]
> and also demo code using Google Colab
> 
> Thanks

Hi! Thanks for your suggestion. We have updated ``run_one_image.py`` and a colab demo for ViTMatte. Maybe you could have a try.

**Comment by albirrkarim** [comment]
Thanks
