### ISSUE TITLE
请问测试可以分显卡跑吗？

### ISSUE THREAD

**Issue by davislee546** [hustvl/ViTMatte#11]
默认只跑一张卡，跑着跑着就会报错"cuda out of memory"

**Comment by JingfengYao** [comment]
目前是不行的。你可以参考[issue 10](https://github.com/hustvl/ViTMatte/issues/10)来尝试降低你测试的显存。

**Comment by davislee546** [comment]
> 目前是不行的。你可以参考[issue 10](https://github.com/hustvl/ViTMatte/issues/10)来尝试降低你测试的显存。

感谢！确实可以！
