### ISSUE TITLE
About gradient_loss and connectivity_error

### ISSUE THREAD

**Issue by Wickked-swag** [hustvl/ViTMatte#21]
I found that the values of connectivity_error and gradient_loss obtained through the MATLAB file of DIM, when processing the results from inference.py, are excessively large. I wonder if these values, connectivity_error and gradient_loss, have been scaled similarly to MSE in the paper? Or is there an issue with my approach? Based on my analysis, if there are problems with the generated data, MSE and SAD should also be incorrect.

**Comment by JingfengYao** [comment]
**The scaling of Conn and Grad has originally been done in Deep Image Matting evaluation.** Its [official codes](https://sites.google.com/view/deepimagematting) did not show that clearly, but you could refer to the evaluation codes of previous famous methods [IndexNet](https://github.com/poppinace/indexnet_matting/blob/master/evaluation_code/hleval.m#L27) and [GCAMatting](https://github.com/Yaoyi-Li/GCA-Matting/blob/master/DIM_evaluation_code/evaluate.m#L22).

In ViTMatte, we follow the same evaluation codes provided above. Besides, we have scaled MSE for ease of clarity.

**Comment by Wickked-swag** [comment]
Thank U.You solved a big doubt for me.
