### ISSUE TITLE
Train Config

### ISSUE THREAD

**Issue by WHHWW** [hustvl/ViTMatte#22]
Excuse me, I'm sorry to bother you 
  https://github.com/hustvl/ViTMatte/blob/63ed4175a7fb9341e43b6c5e460a641b71f07874/configs/common/dataloader.py#L13，Does 'path/to/bg' here refer to the merged folder after compositing, or the directory of the COCO files?

**Comment by JingfengYao** [comment]
It's the path to COCO train2014 files.

**Comment by WHHWW** [comment]
> 这是 COCO train2014 文件的路径。
I see.Thank you for your reply .
