### ISSUE TITLE
trimap

### ISSUE THREAD

**Issue by yellowyi9527** [hustvl/ViTMatte#23]
The need to use trimap is too limited. Have you ever tried not to use it?

**Comment by JingfengYao** [comment]
Matting with trimap is a long-standing problem/experiment setting for **natural** image matting. Here are my suggestions:
1. matting with simple guidance: see [Matte Anything](https://github.com/hustvl/Matte-Anything) for example.
2. matting with image only: see [HAttMatting](https://github.com/yuhaoliu7456/CVPR2020-HAttMatting) or [LFMatting](https://github.com/yunkezhang/FusionMatting) for example.

**Comment by yellowyi9527** [comment]
Thanks for the suggestion
