### ISSUE TITLE
missing "common/optim.py"

### ISSUE THREAD

**Issue by fuqian95** [hustvl/ViTMatte#29]
in the file "configs/common/optimizer.py" line 24, it is:
model_zoo.get_config("common/optim.py").
but there is no file named "optim.py"

**Comment by 99991** [comment]
`common/optim.py` is from detectron2:

https://github.com/facebookresearch/detectron2/blob/8d85329aed8506ea3672e3e208971345973ea761/configs/common/optim.py#L18
