### ISSUE TITLE
finetuning from DINO weights

### ISSUE THREAD

**Issue by kshitijagrwl** [hustvl/ViTMatte#5]
In your train.md doc, you mention about pretrained folder with a preprocess.py script to convert DINO weights for loading into your architecture. 

```
cd ViTMatte/pretrained
python preprocess.py
```
Can you please release this script?

**Comment by JingfengYao** [comment]
Hi, we have updated the script.
You could run 
```
cd ./pretrained
python preprocess.py
```
to get ``dino_vit_s_fna.pth`` and ``mae_vit_b_fna.pth`` for the training.

**Comment by kshitijagrwl** [comment]
thanks!
