### ISSUE TITLE
training weight

### ISSUE THREAD

**Issue by JWSunny** [hustvl/ViTMatte#8]
thanks for your sharing, the training model weight is 1.2G in my dataset，but provide the ViTMatte_xxx.pth is 337M, hwo to convert？

**Comment by JWSunny** [comment]
OK，i solved it~

**Comment by JingfengYao** [comment]
It is introduced in the [train doc](https://github.com/hustvl/ViTMatte/blob/main/docs/train.md).

**Comment by JWSunny** [comment]
how to save the best model in test_data during training process?  can i modify which file，not familiar with detectron2

**Comment by JingfengYao** [comment]
You could integrate evaluating during training by modifying https://github.com/hustvl/ViTMatte/blob/main/main.py#L41.

**Comment by JWSunny** [comment]
can you release the evaluating during training? How do you save the best model during training？

**Comment by JingfengYao** [comment]
We didn't do that. We just simply choose the weights from the last epoch of training as our final weights.

**Comment by JWSunny** [comment]
OK! i see, thanks~
